### ISSUE TITLE
[Feature Request] interactive prompt to select deletion resouces

### ISSUE THREAD

**Issue by yamatatsu** [go-to-k/delstack#3]
It is useful to allow selecting deletion resources as [this](https://dev.to/tidalmigrations/interactive-cli-prompts-in-go-3bj9#how-to-implement-interactive-checkboxes) I think.
ex. `-i, --interactive`

**Comment by go-to-k** [comment]
@yamatatsu 
Hi, yamatatsu-san

Thanks for the feature request.
That sounds like a very nice feature. I'll consider it!

**Comment by go-to-k** [comment]
@yamatatsu 

I have a question for you.

If a CloudFormation stack contains resources other than those selected by the user, do you think the tool should keep those resources and delete the stack and the rest of the resources?
Or do you think it should exit with an error?

**Comment by go-to-k** [comment]
Hmmm...
Should I just leave the stack and terminate with an error, as same as an unsupported resource?🤔

**Comment by go-to-k** [comment]
@yamatatsu 
I have a feeling that it would be better to leave the stack and exit with an error, because if the stack is erased with the resources left behind, it may be impossible to find the resources left behind. If you want to retain those resources and delete the stack, you would probably specify a "Deletion Policy: Retain" for those resources.(Then it will not cause DELETE_FAILED.)

Therefore, I will try to implement it that way for now.

Sorry for the question I posed to you.
